name: Security Check

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  security-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run security checks
        run: |
          bash .ai/scripts/security-check.sh || true

      - name: Run secret detection tests
        run: |
          bash .ai/tests/test-secret-detection.sh || true

      - name: Comment on success
        if: success()
        run: |
          echo "Security checks passed"
